### ISSUE TITLE
Controller runtime breaking change v0.23+ for webhooks init

### ISSUE THREAD

**Issue by gerbil** [kedacore/keda#7413]
### Report

Controller runtime breaking change requires attention -> [v0.23.0](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.23.0)

-> Existing code of the form builder.**WebhookManagedBy(mgr).For(&corev1.Deployment{})** has to be changed to **builder.WebhookManagedBy(mgr, &appsv1.Deployment{})**

### Expected Behavior

Successful build

### Actual Behavior

When trying to build with 0.23+ version we got:
```
# github.com/kedacore/keda/v2/apis/keda/v1alpha1
/home/AzDevOps/go/pkg/mod/github.com/kedacore/keda/v2@v2.18.3/apis/keda/v1alpha1/scaledjob_webhook.go:35:34: not enough arguments in call to ctrl.NewWebhookManagedBy
	have (controllerruntime.Manager)
	want (manager.Manager, T)
/home/AzDevOps/go/pkg/mod/github.com/kedacore/keda/v2@v2.18.3/apis/keda/v1alpha1/scaledobject_webhook.go:61:34: not enough arguments in call to ctrl.NewWebhookManagedBy
	have (controllerruntime.Manager)
	want (manager.Manager, T)
/home/AzDevOps/go/pkg/mod/github.com/kedacore/keda/v2@v2.18.3/apis/keda/v1alpha1/triggerauthentication_webhook.go:40:34: not enough arguments in call to ctrl.NewWebhookManagedBy
	have (controllerruntime.Manager)
	want (manager.Manager, T)
/home/AzDevOps/go/pkg/mod/github.com/kedacore/keda/v2@v2.18.3/apis/keda/v1alpha1/triggerauthentication_webhook.go:47:34: not enough arguments in call to ctrl.NewWebhookManagedBy
	have (controllerruntime.Manager)
	want (manager.Manager, T)
```

### Steps to Reproduce the Problem

1. Upgrade controller-runtime to v0.23
2. Build project with keda used (inside controllers in our case)
3. Observe an error

### KEDA Version

2.18.3

### Kubernetes Version

1.34

### Platform

Microsoft Azure

### Would you be open to contributing a fix?

None
