### PR TITLE
chore: bump k8s.io & controller-runtime dependencies

### LINKED ISSUE #7413: Controller runtime breaking change v0.23+ for webhooks init
### Report

Controller runtime breaking change requires attention -> [v0.23.0](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.23.0)

-> Existing code of the form builder.**WebhookManagedBy(mgr).For(&corev1.Deployment{})** has to be changed to **builder.WebhookManagedBy(mgr, &appsv1.Deployment{})**

### Expected Behavior

Successful build

### Actual Behavior

When trying to build with 0.23+ version we got:
```
# github.com/kedacore/keda/v2/apis/keda/v1alpha1
/home/AzDevOps/go/pkg/mod/github.com/kedacore/keda/v2@v2.18.3/apis/keda/v1alpha1/scaledjob_webhook.go:35:34: not enough arguments in call to ctrl.NewWebhookManagedBy
	have (controllerruntime.Manager)
	want (manager.Manager, T)
/home/AzDevOps/go/pkg/mod/github.com/kedacore/keda/v2@v2.18.3/apis/keda/v1alpha1/scaledobject_webhook.go:61:34: not enough arguments in call to ctrl.NewWebhookManagedBy
	have (controllerruntime.Manager)
	want (manager.Manager, T)
/home/AzDevOps/go/pkg/mod/github.com/kedacore/keda/v2@v2.18.3/apis/keda/v1alpha1/triggerauthentication_webhook.go:40:34: not enough arguments in call to ctrl.NewWebhookManagedBy
	have (controllerruntime.Manager)
	want (manager.Manager, T)
/home/AzDevOps/go/pkg/mod/github.com/kedacore/keda/v2@v2.18.3/apis/keda/v1alpha1/triggerauthentication_webhook.go:47:34: not enough arguments in call to ctrl.NewWebhookManagedBy
	have (controllerruntime.Manager)
	want (manager.Manager, T)
```

### Steps to Reproduce the Problem

1. Upgrade controller-runtime to v0.23
2. Build project with keda used (inside controllers in our case)
3. Observe an error

### KEDA Version

2.18.3

### Kubernetes Version

1.34

### Platform

Microsoft Azure

### Scaler Details

_No response_

### Would you be open to contributing a fix?

None

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mycrEEpy**
… and:

* implement generics in webhooks
* implement new events recorder
* add package `action` for common event actions
* update k8s.io/* to v0.35.1
* update sigs.k8s.io/controller-runtime to v0.23.1
* update github.com/prometheus/common to v0.67.5 (required for expfmt.NewTextParser)

### Checklist

- [ ] When introducing a new scaler, I agree with the [scaling governance policy](https://github.com/kedacore/governance/blob/main/SCALERS.md)
- [x] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [ ] Tests have been added *(if applicable)*
- [x] Ensure `make generate-scalers-schema` has been run to update any outdated generated files
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog), only when the change impacts end users
- [ ] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [ ] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes #7413

### CODE REVIEW

File: pkg/scalers/metrics_api_scaler.go [hunk 1]
```diff
@@ -167,7 +168,7 @@ func getValueFromPrometheusResponse(body []byte, valueLocation string) (float64,
 	}
 
 	reader := strings.NewReader(bodyStr)
-	familiesParser := expfmt.TextParser{}
+	familiesParser := expfmt.NewTextParser(model.LegacyValidation)
```
Comment (mycrEEpy) [inline pkg/scalers/metrics_api_scaler.go:171]: Also, unsure about which `ValidationScheme` to use here..

**Review by mycrEEpy — COMMENTED** [review]
Should we ignore the deprecation of `GetEventRecorderFor` for now to not bloat this PR?

File: pkg/scalers/metrics_api_scaler.go (hunk 1 above)
Comment (JorTurFer) [reply pkg/scalers/metrics_api_scaler.go:171]: Which are the options?

File: go.mod [hunk 2]
```diff
@@ -6,23 +6,23 @@ replace (
 	// we need a version with a proper license
 	github.com/chzyer/logex => github.com/chzyer/logex v1.2.1
 
-	// pin k8s.io to v0.34.3 & sigs.k8s.io/controller-runtime to v0.22.4
+	// pin k8s.io to v0.35.1 & sigs.k8s.io/controller-runtime to v0.23.1
```
Comment (JorTurFer) [inline go.mod:9]: ensure that these deps have the same version outside the replace please

**Comment by JorTurFer** [comment]
> Should we ignore the deprecation of `GetEventRecorderFor` for now to not bloat this PR?

if it's possible, let's solve it here

File: pkg/scalers/metrics_api_scaler.go (hunk 1 above)
Comment (mycrEEpy) [reply pkg/scalers/metrics_api_scaler.go:171]:
```go
// LegacyValidation is a setting that requires that all metric and label names
// conform to the original Prometheus character requirements described by
// MetricNameRE and LabelNameRE.
LegacyValidation

// UTF8Validation only requires that metric and label names be valid UTF-8
// strings.
UTF8Validation
```

File: go.mod (hunk 2 above)
Comment (mycrEEpy) [reply go.mod:9]: They are all on v0.35.1 outside of the replace.
The controller-runtime already was on v0.23.1.
I have also fixed the client-go version which was set to v1.5.2, an old, deprecated version.

**Comment by mycrEEpy** [comment]
> > Should we ignore the deprecation of `GetEventRecorderFor` for now to not bloat this PR?
> 
> if it's possible, let's solve it here

The new `events.EventRecorder` only exposes `Eventf` with two new parameters `related runtime.Object` and `action string`. I've set `related` to nil everywhere for now to keep it simple. For `action` I've added a new package with constants to represent common actions like create, update & delete.
